### ISSUE TITLE
Can't get "DHE-RSA-AES256-SHA" to work for Microsoft SSTP Client.

### ISSUE THREAD

**Issue by kpdozer** [cenk1cenk2/docker-softether-vpnsrv#15] opened 2021-08-12 17:03 UTC
I get error: A fatal error occurred while creating a TLS client credential. The internal error state is 10013
"siomiz/SoftEtherVPN" works with "DHE-RSA-AES256-SHA" without issue. What can be done?

**Comment by malikshi** [comment] 2021-08-12 17:53
@kpdozer set `ServerCipherSet DHE-RSA-AES256-SHA` recommended to use `ECDHE-RSA-AES256-GCM-SHA384`

**Comment by malikshi** [comment] 2021-08-12 18:10
@cenk1cenk2 sir can you test it?

**Comment by cenk1cenk2** [comment] 2021-08-12 18:36
hello @kpdozer and @malikshi ,

thank you @malikshi for the suggestion on this problem. I really do not know how to replicate this problem. I have an ongoing setup for the last 6-7 years and am using it with multiple operating system clients but never really needed to fine-tune it. So, unfortunately, I am not an expert on the issue. But if some kind of library is missing from the container, we can always add that with a suggestion.

**Comment by malikshi** [comment] 2021-08-13 00:08
can you try this edit this one in [server_config.json](https://github.com/cenk1cenk2/docker-softether-vpnsrv/blob/master/build/vpn_server.config) changes default CipherName to `string CipherName ECDHE-RSA-AES256-GCM-SHA384` @kpdozer edit and save with your own set then run [docker-compose](https://github.com/cenk1cenk2/docker-softether-vpnsrv#docker-compose)

**Comment by malikshi** [comment] 2021-08-13 07:57
@kpdozer  you may check this setting for windows client [enable deprecated protocol tls](https://blog.matrixpost.net/a-fatal-error-occurred-while-creating-a-tls-client-credential-the-internal-error-state-is-10013/#:~:text=The%20internal%20error%20state%20is%2010013,-by%20Marcus%20Rath&text=If%20you%20have%20disabled%20the,further%20down%20for%20security%20reasons.&text=These%20old%20versions%20of%20TLS,broken%2C%20and%20contain%20other%20flaws.) then you're good to go.

**Comment by kpdozer** [comment] 2021-08-16 12:53
@malikshi Thanks. Indeed ECDHE-RSA-AES256-GCM-SHA384 or any other ECDHE method works. It just became interesting why I could not choose the method recommended by siomiz. In addition, I did not make any settings on the Windows client side. I think that ECDHE-RSA-AES256-GCM-SHA384 will be enough for me, so the problem can be considered solved.

**Comment by malikshi** [comment] 2021-08-16 17:11
I'm lacking knowledge of docker things, any reference to study docker? mostly apps/services that I'm doesn't use docker sad noises

**Comment by malikshi** [comment] 2021-08-16 17:52
how to download ovpn.zip from the inside container? @cenk1cenk2 sorry to bother you

**Comment by cenk1cenk2** [comment] 2021-08-16 17:59
You don't have to say that @malikshi. You can use [`docker-compose cp`](https://docs.docker.com/engine/reference/commandline/compose_cp/) or [`docker cp`](https://docs.docker.com/engine/reference/commandline/cp/) command. The exact folder which it is in I have no idea at the moment, but you can try to `docker exec` into the container to find out.

About docker itself, you can take a look at Linux kernel namespaces to understand the basic underpinnings of containerization but other than that docker reference pages are pretty good.

**Comment by malikshi** [comment] 2021-08-16 18:20
thank you so much @cenk1cenk2 I set up softether with your docker and make adjustments for my personal settings.
currently still running softether + ics-dhcp server and have speed problem I don't know the causes is.

**Comment by cenk1cenk2** [comment] 2021-08-17 10:30
I thank you  @malikshi  for the suggestion.

@kpdozer , I am closing this issue as it is resolved.

**Closed by cenk1cenk2** 2021-08-17 10:30 UTC
